#define PROJECTOR_ON         0x55
#define PROJECTOR_OFF        0x66
#define RANGE_PKT            0x44
#define UNLOCK_PKT           0x01
#define PROJECTOR_MOTOR_DOWN 0x33
#define PROJECTOR_MOTOR_UP   0x22
#define ALARM_OFF            0x05
#define ALARM_ON             0x06
#define DEMO_ALARM_ON        0x16
#define DEMO_ALARM_OFF       0x15
#define DEMO_ALARM_ARMED     0X17
#define DEMO_ALARM_DISARMED  0x18
#define QUEST_ON             0x77
#define QUEST_OFF            0x88

#define Reponse_A            0x90
#define Reponse_B            0x91
#define Reponse_C            0x92
#define Reponse_D            0x93